### ISSUE TITLE
StageRecovery Hindering KSP performance in VAB and SPH

### ISSUE THREAD

**Issue by ProwlerProwl** [linuxgurugamer/StageRecovery#7]
Hi,

I have detected the following error while using Stage Recovery on my modded KSP. I have added and removed SR and the issue seems to go away with uninstalling SR. The error starts when you exit VAB or SPH to launchpad and revert back to VAB or SPH. From there it starts hindering performance. Alt-F12 shows 

[ERR 00:40:32.005] StageRecovery: No parent part found
[ERR 00:40:32.018] StageRecovery: No parent part found
[ERR 00:40:32.030] StageRecovery: No parent part found
spammed.....

The usual time of transition is less than 5 seconds usually. With SR loaded it takes more than 10 minutes to load. Please help me capture whatever data you need to resolve this lagging and freezing issue.

Once this happens adding or removing parts in VAB or SPH become sluggish tasks that take minutes. Also setting up your action groups starts to spam null reference errors indefinitely when you use it. I think it has to do with my mod list but I am not sure.

Can you please help me determine what is happening and how to troubleshoot?

Best regards,

**Comment by linuxgurugamer** [comment]
To start, I need the full log file.   Also the craft file, as it is when you are ready to launch.
The problem is happening because at some point SR is looking for a decoupler on the vessel, and it can't find any, but it shouldn't be spamming the log.

If you try one of the stock vessels, does it happen?

Regarding log files, refer to this post to help find the correct file:

http://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/

**Comment by linuxgurugamer** [comment]
After some more digging, it almost looks like you have a circular reference in the craft file.  This error should never occur

**Comment by ProwlerProwl** [comment]
That points me in the direction of two craft files where I am using a engine mount which is basically an upside-down decoupler. I attach all files requested into MyJunkyJunk.zip

**Comment by ProwlerProwl** [comment]
[MyJunkyJunk.zip](https://github.com/linuxgurugamer/StageRecovery/files/4072626/MyJunkyJunk.zip)

**Comment by ProwlerProwl** [comment]
This Making History parts might be related as well as tweakscale throwing a tantrum early on. I will try stock crafts to see if I can recreate the issue. If not then I will add the making history engineplate and try again to see if it acts up.
[Making History issues early on.zip](https://github.com/linuxgurugamer/StageRecovery/files/4073214/Making.History.issues.early.on.zip)

**Comment by ProwlerProwl** [comment]
It does appear to happen with stock craft files too.

**Comment by linuxgurugamer** [comment]
Please make a new install, and only add StageRecovery and the dependencies.  You have a lot of mods, you need to reduce the number of mods to the minimum necessary to get the error

**Comment by ProwlerProwl** [comment]
Understood, I installed SR with dep. tested and all is peaches. I will start adding my mod list on a "single to SR" comparison until I see the error.

**Comment by ProwlerProwl** [comment]
After installing the SR and Dependencies, I installed Mechjeb and ran KSP for the second time, after a fresh install of KSP-Making History-Breaking Ground. The game crashed and will not load. Went back to uninstall Mechjeb and tried to reload. crashed again and will not load. Decided to scrap the fresh install and start over. Installed KSP-Making History-Breaking Ground again, went to CKAN and installed Stage Recovery and Dependencies, Loaded the game for the first time with SR and crashed the same way.

Attached the logfiles in Scuad.zip

After the crash decided to go back to CKAN and unistalled SR with Dep. The game loaded. "Strange..."
[Squad.zip](https://github.com/linuxgurugamer/StageRecovery/files/4078533/Squad.zip)

**Comment by linuxgurugamer** [comment]
Install ZeroMiniAVC.  The crashes are from the MiniAVC.dll, it's broken.  ZeroMiniAVC will remove them.
If it crashes, then just run it again, you should be fine

**Comment by ProwlerProwl** [comment]
Thank you. Doing a reinstal of ZeroMiniAVC via CKAN has solved all my issues. This had been driving me crazy since 1.7.3 I have been unable to have a steady build since then. No wonder I could not find the fault to isolate the issue. There were many culprits involved throwing my judgment off.

Thanks again and I hope someone finds this information useful for future issues.
